#include <stdint.h>
int32_t nmViewsCreated(void);
int32_t nmReleaseCalls(void);
void nmTouch(int32_t tag, int32_t phase);
void nmTeardown(void);
int32_t nmLoop(void);
void nmMount(void);
void nmResize(float width, float height);
void nmScroll(int32_t tag, float x, float y, float width, float height, float contentWidth, float contentHeight);
int32_t nmLastScrollTag(void);
float nmContentWidth(void);
float nmContentHeight(void);
float nmScrolledX(void);
float nmScrolledY(void);
int32_t nmScrolledAnimated(void);
int32_t nmContentSizeWrites(void);
int32_t nmScrollFrameWrites(void);
int32_t nmScreenHeightReads(void);
int32_t nmTransformWrites(void);
float nmVisualX(int32_t tag, float x);
float nmVisualY(int32_t tag, float y);
float nmLayoutWidth(int32_t tag);
float nmRotation(int32_t tag);
float nmOpacity(int32_t tag);
float nmTranslateX(int32_t tag);
float nmLayoutHeight(int32_t tag);
void nmTouchAt(float x, float y, int32_t phase);
int32_t nmLastPressableTag(void);
float nmLayoutX(int32_t tag);
float nmLayoutY(int32_t tag);
int32_t nmRestackWrites(void);
int32_t nmAddChildWrites(void);
int32_t nmDetachWrites(void);
int32_t nmPaintTag(int32_t parentTag, int32_t index);
int32_t nmPaintTextIndex(int32_t parentTag, const char *text);
void nmControl(int32_t tag, int32_t phase, const char *value);
void nmControlSized(int32_t tag, int32_t phase, const char *value, float width, float height);
void nmEnvironment(float keyboardHeight, int32_t dark);
int32_t nmLastInputTag(void);
int32_t nmFocused(int32_t tag);
const char *nmProp(int32_t tag, const char *name);
int32_t nmLastControlTag(int32_t kind);
float nmTextWidth(const char *text);
float nmTextHeight(const char *text);
float nmTextVisualX(const char *text);
float nmTextVisualY(const char *text);
float nmScrollOffsetX(int32_t tag);
float nmScrollOffsetY(int32_t tag);
int32_t nmScrollShifts(void);
void nmAppReply(const char *name, const char *value);
const char *nmAppLog(void);
void nmAppLogClear(void);
int32_t nmAppEvent(int32_t kind, const char *value);
float nmBackgroundAlpha(int32_t tag);
int32_t nmLastViewTag(void);
const char *nmAnyProp(const char *name);
int32_t nmTagWithProp(const char *name, const char *value);
int32_t nmHasLabel(const char *text);
